Rename IbisSource to FrankFramework
frankframework/frank-doc pull request #176
Opened 2024-02-27 15:39 UTC by nielsm5

2024-02-27 15:50 UTC, jkosternl requested changes

2024-02-27 15:50 UTC, jkosternl commented on pom.xml
>  		</developer>
We should add Martijn too, since he build most of it, right?

2024-02-27 15:50 UTC, jkosternl commented on pom.xml
> +					<executions>
You've deleted `<version>3.6.3</version>` in the first pom, but didn't add it here, so it falls back to an older not pinned version. 
Please add this line here: `<version>3.6.3</version>`

2024-02-27 16:43 UTC, jkosternl commented on pom.xml
>  		</developer>
Oh oops... the collapsing did work too good 😉 .. sorry.

2024-02-27 16:44 UTC, jkosternl approved these changes
Good changes!

2024-02-27 21:26 UTC, philipsens requested changes

2024-02-27 21:26 UTC, philipsens commented on pom.xml
> +			<email>sergi@frankframework.nl</email>
```suggestion
			<email>sergi@frankframework.org</email>
```

2024-02-28 14:46 UTC, philipsens approved these changes

2024-02-28 14:48 UTC, merged