Highlight literal text using code blocks
frankframework/frank-doc pull request #198
Opened 2024-08-23 11:04 UTC by thomaspj10

Closes #195 

Old:
![image](https://github.com/user-attachments/assets/56eecfbe-276c-4364-a970-a79291967d38)

New:
![image](https://github.com/user-attachments/assets/c1c222ad-e2ac-4722-a87f-bb316c3fe331)

2024-08-26 08:31 UTC, mhdirkse requested changes

2024-08-26 08:31 UTC, mhdirkse commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_VALUE_START_DELIMITER, JAVADOC_SUBSTITUTION_PATTERN_STOP_DELIMITER, s -> "<code>" + getClassFieldValueReplacement(s, context) + "</code>");
Ik herinner me niet meer hoe deze code precies werkt, dus neem niet zomaar aan wat ik hier opmerk. Is het een idee om de `<code>` en `</code>` tags op ge nemen in functie `getClassFieldValueReplacement()`?

2024-08-28 09:04 UTC, nielsm5 reviewed
Ik snap de test cases niet helemaal...

2024-08-28 09:30 UTC, evandongen commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_VALUE_START_DELIMITER, JAVADOC_SUBSTITUTION_PATTERN_STOP_DELIMITER, s -> "<code>" + getClassFieldValueReplacement(s, context) + "</code>");
Zo te zien is dit de enige plek waar `getClassFieldValueReplacement` gebruikt wordt. Ik zou het dan logischer vinden om in die method (bv op regel 299) het resultaat te wrappen met code tags

2024-08-29 05:16 UTC, evandongen approved these changes

2024-08-29 05:17 UTC, evandongen approved these changes

2024-08-29 15:21 UTC, nielsm5 approved these changes
De xsd ziet er goed uit.

2024-08-29 15:21 UTC, merged