Properly display Javadoc code blocks
frankframework/frank-doc pull request #199
Opened 2024-08-23 13:39 UTC by thomaspj10

Closes #196 

Example: The code blocks of `FixedResultPipe` properly work now.
![image](https://github.com/user-attachments/assets/93b61de1-d7e3-4032-b4ab-802116b181b4)

I tested the FrankDoc with the changes from https://github.com/frankframework/frankframework/issues/7273

I removed the exception in favor of a warning, because the entire FrankDoc doesn't built when the FF contains one malformed Javadoc tag (`{@code <Pipe></Pipe>`) for example.

2024-08-26 08:35 UTC, mhdirkse requested changes

2024-08-26 08:35 UTC, mhdirkse commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Description.java
> +			return Utils.replaceClassCodeValue(Utils.replaceClassFieldValue(result, clazz));
Ik zou graag willen dat deze wijziging wordt gecoverd met tests. De Frank!Doc is ingewikkeld, en de testen zijn een belangrijke bron van documentatie.

2024-08-28 09:07 UTC, evandongen commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		while (startIndex >= 0) {
Misschien wel de moeite om ergens in een comment toe te voegen waarom dit zo werkt

2024-08-28 09:07 UTC, evandongen commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_LITERAL_START_DELIMITER, s -> s.replaceAll("<", "&lt;").replaceAll(">", "&gt;"));
Kan je hier mogelijk `org.apache.commons.text.StringEscapeUtils` voor gebruiken? Bijvoorbeeld `escapeHtml4`.

2024-08-28 09:17 UTC, nielsm5 commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +			int stopIndex = text.indexOf("}", startIndex);
```suggestion
			int stopIndex = text.indexOf(JAVADOC_SUBSTITUTION_PATTERN_STOP_DELIMITER, startIndex);
```
Wel zo netjes toch de constanten te gebruiken ;)

2024-08-28 09:17 UTC, nielsm5 commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_LITERAL_START_DELIMITER, s -> s.replaceAll("<", "&lt;").replaceAll(">", "&gt;"));
Al deze replaces moeten alle html special chars vervangen (dus niet alleen `<` en `>`)

2024-08-28 09:17 UTC, nielsm5 commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_LITERAL_START_DELIMITER, s -> s.replaceAll("<", "&lt;").replaceAll(">", "&gt;"));
En zet de literal er nu een ` omheen?

2024-08-28 14:11 UTC, thomaspj10 commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +		return replacePattern(text, JAVADOC_LITERAL_START_DELIMITER, s -> s.replaceAll("<", "&lt;").replaceAll(">", "&gt;"));
Een literal zet er niks omheen. Ik heb de functionaliteit van de javadoc (https://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javadoc.html#%7B@literal%7D) gekopieerd.

2024-08-29 15:39 UTC, nielsm5 commented
De xsd diff die hier uit komt klopt niet helemaal volgens mij. 
Voorheen:
![image](https://github.com/user-attachments/assets/4e4a96ec-05ce-408d-92d1-4233973a4bc6)
Nu:
![image](https://github.com/user-attachments/assets/a1622cb6-872a-4ee9-bc88-dbef1e064ef1)

2024-08-30 08:07 UTC, thomaspj10 commented
Ik heb inderdaad een fout gemaakt bij code blocks. In de foute implementatie verwijderde ik enkel {@code }. Dit zag er nog goed uit, omdat er bij multi line code blocks een `<pre></pre>` tag omheen zit, zodat de lijnen goed wrappen.

Bij de attribute `hideRegex` ging dit bijvoorbeeld fout, omdat hier geen `<code></code>` block omheen gewrapped worden.

2024-08-30 09:11 UTC, evandongen commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +	private static String getCodeValueReplacement(String codeBlock) {
Misschien mis ik hier iets, maar dit zorgt toch weer voor andere output? Oude situatie was bv de platte string 'true', dat wordt nu '<code>true</code>', is dat dan wel wenselijk?

2024-08-30 09:53 UTC, evandongen commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
> +	private static String getCodeValueReplacement(String codeBlock) {
Ok, helemaal goed, ik doelde vooral op de plaatjes van Niels hierboven

2024-08-30 09:54 UTC, evandongen approved these changes

2024-09-03 08:43 UTC, thomaspj10 commented
Fixed the following bugs:
- White space, newlines and tabs are removed from the start and end of javadoc tags. `{@code\n content}` becomes `<code>content</code>`.
- `{@code, {@literal and {@value` now also work inside the documentation of enum values.

2024-09-03 09:38 UTC, evandongen approved these changes

2024-09-04 09:07 UTC, nielsm5 commented on frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Description.java
> +		if (!StringUtils.isBlank(result)) {
En early returns zijn mooier, dan heb je minder nesting ;)

2024-09-04 09:07 UTC, nielsm5 approved these changes

2024-09-04 09:07 UTC, merged